type t

external plan: int -> unit = "" [@@bs.send.pipe: t]
external end_: (_ [@bs.as 0]) -> unit = "end" [@@bs.send.pipe: t]
external end_error: Js.Exn.t -> unit = "end" [@@bs.send.pipe: t]
external fail: string -> unit = "" [@@bs.send.pipe: t]
external pass: string -> unit = "" [@@bs.send.pipe: t]
external timeoutAfter: int -> unit = "" [@@bs.send.pipe: t]
external skip: string -> unit = "" [@@bs.send.pipe: t]
external ok: 'value -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external notOk: 'value -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external error: Js.Exn.t Js.Nullable.t -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external equal: 'actual -> 'expected -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external notEqual: 'actual -> 'expected -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external deepEqual: 'actual -> 'expected -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external notDeepEqual: 'actual -> 'expected -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external deepLooseEqual: 'actual -> 'expected -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external notDeepLooseEqual: 'actual -> 'expected -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external throws: ('a -> 'b) -> ?expected:Js.Exn.t -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external doesNotThrow: ('a -> 'b) -> ?expected:Js.Exn.t -> ?msg:string -> unit = "" [@@bs.send.pipe: t]
external test: string -> ?options:TestOptions.t -> (t -> unit) -> unit = "" [@@bs.send.pipe: t]
external comment: string -> unit = "" [@@bs.send.pipe: t]
